site_name: Keskitetty dokumentaatio
site_url: https://panualaluusua.github.io/docs/
# Tämä on tärkein asetus, jotta kaikki polut ja linkit toimivat oikein aliurlissa
extra:
  base_url: /docs
theme:
  name: material
# nav-osio poistettu, koska awesome-pages-plugin rakentaa navigaation automaattisesti kansiorakenteen perusteella
plugins:
  - search
  - awesome-pages
  - mermaid
markdown_extensions:
  - pymdownx.superfences
  - attr_list
