/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  projekti1Sidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Autogeneroi tämän dokumentaatioinstanssin juuresta
    },
  ],
};
module.exports = sidebars;