export default {
  "17896441": [() => import(/* webpackChunkName: "17896441" */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  "2e7fb06b": [() => import(/* webpackChunkName: "2e7fb06b" */ "@generated/docusaurus-plugin-content-docs/projekti1/p/docs-projekti-1-531.json"), "@generated/docusaurus-plugin-content-docs/projekti1/p/docs-projekti-1-531.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/projekti1/p/docs-projekti-1-531.json")],
  "4c1c400b": [() => import(/* webpackChunkName: "4c1c400b" */ "@generated/docusaurus-plugin-content-docs/projekti1/__plugin.json"), "@generated/docusaurus-plugin-content-docs/projekti1/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/projekti1/__plugin.json")],
  "5e95c892": [() => import(/* webpackChunkName: "5e95c892" */ "@theme/DocsRoot"), "@theme/DocsRoot", require.resolveWeak("@theme/DocsRoot")],
  "a2065270": [() => import(/* webpackChunkName: "a2065270" */ "@generated/docusaurus-plugin-content-docs/default/p/docs-docs-fbb.json"), "@generated/docusaurus-plugin-content-docs/default/p/docs-docs-fbb.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/p/docs-docs-fbb.json")],
  "a7bd4aaa": [() => import(/* webpackChunkName: "a7bd4aaa" */ "@theme/DocVersionRoot"), "@theme/DocVersionRoot", require.resolveWeak("@theme/DocVersionRoot")],
  "a94703ab": [() => import(/* webpackChunkName: "a94703ab" */ "@theme/DocRoot"), "@theme/DocRoot", require.resolveWeak("@theme/DocRoot")],
  "aba21aa0": [() => import(/* webpackChunkName: "aba21aa0" */ "@generated/docusaurus-plugin-content-docs/default/__plugin.json"), "@generated/docusaurus-plugin-content-docs/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/__plugin.json")],
  "b0d6b393": [() => import(/* webpackChunkName: "b0d6b393" */ "@site/docs/projekti1/docs/dokumentti.md"), "@site/docs/projekti1/docs/dokumentti.md", require.resolveWeak("@site/docs/projekti1/docs/dokumentti.md")],};
